<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FamiliesSeeder extends Seeder
{
    public function run()
    {
        DB::table('families')->insert([
            [

                'alias' => 'Family of Abu Ahmed',
                'public_region' => 'Gaza',
                'information' => 'This family of 8 lost their house during the recent events and urgently needs support for rent and food.',
                'img' => 'storage/home/1.jpg',
                'members_count' => 15,
                'status' => 'active',
                'donated' => 50,
                'goal' => 200,
                'real_name' => 'Ahmed Abu Ahmed',
                'address' => 'Al-Rimal St, Gaza City',
                'phone' => '0599123456',
                'income' => 250.50,
                'notes' => 'Family has health issues; father has chronic illness.',
                'national_id_encrypted' =>'123456789',
                'kyc_documents' => json_encode(['kyc_docs/doc1.pdf', 'kyc_docs/doc2.pdf']),
                'verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alias' => 'Widowed Mother Rania',
                'public_region' => 'Khan Younis',
                'information' => 'Rania is raising 6 children alone. She needs monthly support to provide school supplies and healthy meals.',
                'img' => 'storage/home/Rectangle 31ذ.png',
                'members_count' => 10,
                'status' => 'active',
                'donated' => 30,
                'goal' => 100,
                'real_name' => 'Rania Khalil',
                'address' => 'Khan Younis St, Khan Younis',
                'phone' => '0599876543',
                'income' => 180.00,
                'notes' => 'Mother of six children, no stable income.',
                'national_id_encrypted' => '987654321',
                'kyc_documents' => json_encode(['kyc_docs/doc3.pdf']),
                'verified' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alias' => 'Elderly Couple – Medical Needs',
                'public_region' => 'Al-Zawaida',
                'information' => 'An elderly couple suffering from chronic illness, requiring urgent medication and healthcare assistance.',
                'img' => 'storage/home/photo.png',
                'members_count' => 12,
                'status' => 'active',
                'donated' => 20,
                'goal' => 80,
                'real_name' => 'Mohammed & Fatima',
                'address' => 'Al-Zawaida Street, Al-Zawaida',
                'phone' => '0599234567',
                'income' => 120.00,
                'notes' => 'Elderly couple with chronic illnesses.',
                'national_id_encrypted' => '456789123',
                'kyc_documents' => json_encode(['kyc_docs/doc4.pdf']),
                'verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alias' => 'Family of Four – Education Support',
                'public_region' => 'Al-Nuseirat',
                'information' => 'This family struggles to cover tuition fees and basic needs for their two school-aged children, facing increasing financial pressure due to unemployment and limited access to stable income sources. They urgently need support to ensure their children can continue their education without interruption.',
                'img' => 'storage/home/15.jpg',
                'members_count' => 12,
                'status' => 'active',
                'donated' => 20,
                'goal' => 80,
                'real_name' => 'Hassan Family',
                'address' => 'Al-Nuseirat Camp, Gaza',
                'phone' => '0599001122',
                'income' => 200.00,
                'notes' => 'Children need school supplies.',
                'national_id_encrypted' => '321654987',
                'kyc_documents' => json_encode([]),
                'verified' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alias' => 'Disabled Young Man – Mobility Aid',
                'public_region' => 'Deir al-Balah',
                'information' => 'A young man with disability requires a wheelchair and medical equipment to improve his daily life, as his current condition limits his mobility and independence.',
                'img' => 'storage/home/17.jpg',
                'members_count' => 12,
                'status' => 'active',
                'donated' => 20,
                'goal' => 80,
                'real_name' => 'Yousef Samir',
                'address' => 'Deir al-Balah',
                'phone' => '0599112233',
                'income' => 150.00,
                'notes' => 'Requires wheelchair and mobility aid.',
                'national_id_encrypted' => '654987321',
                'kyc_documents' => json_encode(['kyc_docs/doc5.pdf']),
                'verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alias' => 'Large Family – Food Insecurity',
                'public_region' => 'Al-Zawaida',
                'information' => 'A family of 9 members is struggling to secure daily meals. They need urgent food parcels and nutrition support to meet their basic dietary needs.',
                'img' => 'storage/home/Rectangle 31يؤي.png',
                'members_count' => 17,
                'status' => 'active',
                'donated' => 20,
                'goal' => 80,
                'real_name' => 'Salah Family',
                'address' => 'Al-Zawaida',
                'phone' => '0599445566',
                'income' => 100.00,
                'notes' => 'Large family struggling with food insecurity.',
                'national_id_encrypted' => '789123456',
                'kyc_documents' => json_encode([]),
                'verified' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
             [
                'alias' => 'Abu Mohmmed',
                'public_region' => 'Al-Zawaida',
                'information' => 'A young man with disability requires a wheelchair and medical equipment to improve his daily life, as his current condition limits his mobility and independence.',
                'img' => 'storage/home/6m8CBstirhTpGTYBqjTCLvYDRSru3FOvPUOXEkDC.jpg',
                'members_count' => 12,
                'status' => 'active',
                'donated' => 0,
                'goal' => 80,
                'real_name' => 'ahmed',
                'address' => 'Gaza- AL-Samer',
                'phone' => '0592280338',
                'income' => 150.00,
                'notes' => 'plesa donation for me',
                'national_id_encrypted' => '654987321',
                'kyc_documents' => json_encode(['kyc_docs/doc5.pdf']),
                'verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],


        ]);
    }
}
